# Generated by Django 3.1.1 on 2020-10-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_star', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('user_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.IntegerField(default=0)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
        ),
    ]
