# Generated by Django 3.1.1 on 2020-10-19 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seven_star', '0002_userdata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userData',
            new_name='user_data',
        ),
    ]
