# Generated by Django 3.1.1 on 2020-10-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_star', '0003_auto_20201019_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_finance_data',
            fields=[
                ('finance_id', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('stock_code', models.CharField(max_length=20)),
                ('total_assets_turnover', models.CharField(max_length=200)),
                ('rota', models.CharField(max_length=200)),
                ('total_assets', models.CharField(max_length=200)),
                ('total_liabilities', models.CharField(max_length=200)),
                ('asset_liability_ratio', models.CharField(max_length=200)),
                ('net_profit', models.CharField(max_length=200)),
                ('net_assets', models.CharField(max_length=200)),
                ('roe', models.CharField(max_length=200)),
                ('total_profit', models.CharField(max_length=200)),
                ('current_ratio', models.CharField(max_length=200)),
                ('net_assets_per_share', models.CharField(max_length=200)),
                ('operating_income_per_share', models.CharField(max_length=200)),
                ('enterprise_value', models.CharField(max_length=200)),
                ('equity_multiplier', models.CharField(max_length=200)),
                ('cash_return', models.CharField(max_length=200)),
                ('quick_ratio', models.CharField(max_length=200)),
                ('sale_net_profit', models.CharField(max_length=200)),
                ('forecast_earnings', models.CharField(max_length=50)),
                ('forecast_net_profit', models.CharField(max_length=50)),
                ('forecast_main_business_income', models.CharField(max_length=50)),
                ('forecast_earnings_before_tax', models.CharField(max_length=50)),
                ('forecast_cash_flow', models.CharField(max_length=50)),
                ('forecast_total_profit', models.CharField(max_length=50)),
                ('forecast_operating_profit', models.CharField(max_length=50)),
            ],
        ),
    ]
