# Generated by Django 3.1.1 on 2020-10-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seven_star', '0005_auto_20201026_1041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_basic_information',
            old_name='credit_name',
            new_name='stock_name',
        ),
        migrations.AddField(
            model_name='company_finance_data',
            name='total_share_capital',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
